### PR TITLE
Gesso 4 compatibility

### PR DESCRIPTION
**Pull request by kmonahan**
For the new version of Gesso to be installed successfully, the Gesso Helper module, on which the theme depends, has to be installed before the theme is enabled. Since 'gesso' is included in the profile themes list (which are enabled before the custom whiplash install steps), moves gesso_helper from a custom step to the profile modules list.

### CODE REVIEW

**Comment by dcmouyard** [comment]
I still ran into the following error with this fix:
```
Configuration validation
- The configuration synchronization failed validation.
- Unable to install the <em class="placeholder">Gesso</em> theme since it requires the <em class="placeholder"></em> theme.
```

I thought perhaps adding `- components` to the install list in `whiplash.info.yml` might solve it, but I still got the error.

**Comment by kmonahan** [comment]
@dcmouyard Is that with an existing project? I tested with a fresh install of Whiplash and the latest Gesso, following the instructions at https://forumone.atlassian.net/wiki/spaces/TECH/pages/884539838/Drupal+Starter+Build+Whiplash. What I saw prior to this fix was an error where Gesso could not be enabled because it depended on the Gesso Helper module.

**Comment by dcmouyard** [comment]
@kmonahan Yep, the error I got was with an existing project.

**Comment by gbeezus** [comment]
I can confirm the changes here ensure gesso is installed correctly when performing `drush si whiplash`

**Pull request merged**
